require('../ciencias/formales')
require('../ciencias/lenguaje')
require('../ciencias/sociales')
require('../ciencias/administracion')
require('../ciencias/cognitivas')
require('../ciencias/empircoNaturales')
require('../ciencias/empiricas')
